[package]
name = "prest-embed-utils"
version = "0.1.0"
edition = "2021"
description = "fork of embed utils from rust-embed"
license = "MIT OR Apache-2.0"

[lib]
path = "lib.rs"

[dependencies]
walkdir = "2.3.1"
sha2 = "0.10.5"
mime_guess = "2.0.4"
globset = "0.4.8"

[features]
lazy-embed = []
